name: Build and deploy documentation

on:
  push:
    branches:
      - 'main'
      - 'beta'
      - 'release'
  pull_request:
  release:
    types:
      - released

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# We need contents: write to upload the documentation as a release asset.
permissions:
  contents: write
  pages: write
  id-token: write

env:
  WORKFLOWS_DIR: .github/workflows
  DOCS_DIR: docs
  DOCS_BUILD_DIR: docs/_build/html

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # fetches tags, required for version info
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Build lambeq
      run: pip install .
    - name: Install documentation dependencies
      run: |
        sudo apt-get install graphviz pandoc
        pip install -r docs/requirements.txt
    - name: Draw diagrams from PlantUML files
      uses: Timmy/plantuml-action@v1
      with:
        args: '-v -DPLANTUML_LIMIT_SIZE=8192 -tpng ${{ env.DOCS_DIR }}/puml/*.puml -o img'
    - name: Build documentation
      run: ${{ env.WORKFLOWS_DIR }}/build-docs
    - name: Save documentation as artifact
      if: ${{ github.event_name != 'release' }}
      uses: actions/upload-artifact@v4
      with:
        name: docs_html
        path: ${{ env.DOCS_BUILD_DIR }}
    - name: Upload artifact
      if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'release') }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.DOCS_BUILD_DIR }}
    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'release') }}
      id: deployment
      uses: actions/deploy-pages@v4
    - name: (on release) Zip up documentation to store as release asset
      if: ${{ github.event_name == 'release' }}
      run: |
        tar -cavf lambeq-docs-${{ github.event.release.tag_name }} -C ${{ env.DOCS_BUILD_DIR }} .
    - name: (on release) Add documentation artifact as release asset
      if: ${{ github.event_name == 'release' }}
      run: gh release upload ${{ github.event.release.tag_name }} lambeq-docs-${{ github.event.release.tag_name }} --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
